name: store_x
description: Simplify Caching in Flutter.
version: 0.0.1
homepage: https://github.com/ftkhanft/store_x

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  encrypt: ^5.0.1
  flutter:
    sdk: flutter
  helpers: ^1.1.4
  parse_server_sdk: ^3.1.0
  shared_preferences: ^2.0.9

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  lints: ^1.0.1
